### ISSUE TITLE
Flask not working

### ISSUE THREAD

**Issue by rmsferreira** [ail-project/ail-framework#12]
I`m deploying a fresh AIL but when try to run the server the flask server wont run.

this is the error:

Misp not connected
The HIVE not connected
VT submission is disabled
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Splash_Manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Flask_server.py", line 41, in <module>
    from blueprints.crawler_splash import crawler_splash
  File "/opt/ail-framework/var/www/blueprints/crawler_splash.py", line 28, in <module>
    import crawlers
  File "/opt/ail-framework//bin/lib/crawlers.py", line 41, in <module>
    splash_manager_url = config_loader.get_config_str('Splash_Manager', 'splash_url')
  File "/opt/ail-framework//bin/lib/ConfigLoader.py", line 45, in get_config_str
    return self.cfg.get(section, key_name)
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Splash_Manager'

**Comment by Terrtia** [comment]
Hi @rmsferreira !
Thanks for the report !

Fixed with eec579c5d45bdf7abbf1359ad514d59340933f32
