### ISSUE TITLE
[Search] Function not working, 500-Internal Server Error

### ISSUE THREAD

**Issue by TonyJabbour** [ail-project/ail-framework#120]
How this error happened: while AIL indexing vm crashed and when started AIL again everything was good but search wasn't working at all and the indexing workers or queues didnt continue where ail stopped:

in the  `screen -r Flask_AIL` we notice this:

```csharp
[2021-08-11 16:02:09,982] ERROR in app: Exception on /search [POST]
Traceback (most recent call last):
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "./modules/Role_Manager.py", line 68, in decorated_view
    return func(*args, **kwargs)
  File "/home/ail/project/ail-framework/var/www/modules/search/Flask_search.py", line 124, in search
    ix = index.open_dir(selected_index)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint 
    return read_varint(self.read)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found
IP - - [11/Aug/2021 16:02:09] "POST /search HTTP/1.1" 500 -
```

**Comment by TonyJabbour** [comment]
plus the Screen "Indexer" throwing this error:

```
Traceback (most recent call last):
  File "./Indexer.py", line 161, in <module>
    module = Indexer()
  File "./Indexer.py", line 92, in __init__
    if not exists_in(self.indexpath):
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 136, in exists_in
    ix = open_dir(dirname, indexname=indexname)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint 
    return read_varint(self.read)
  File "/home/ail/project/ail-framework/AILENV/lib/python3.6/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by TonyJabbour** [comment]
Update: I deleted the `indexdir `and let AIL recreate the folder, this fixed the issue i can enter the search but all indexed data gone and i cant search into the items anymore and AIL not indexing them at all.
