### ISSUE TITLE
markupsafe breaking change in minor version 2.1.0

### ISSUE THREAD

**Issue by gallypette** [ail-project/ail-framework#138]
The install script crashes when creating the admin user:
```
~/ail-framework/var/www ~/ail-framework
Traceback (most recent call last):
  File "create_default_user.py", line 13, in <module>
    from Role_Manager import create_user_db, edit_user_db, get_default_admin_token, gen_password
  File "/root/ail-framework/var/www/modules/Role_Manager.py", line 14, in <module>
    from flask_login import LoginManager, current_user, login_user, logout_user, login_required
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask_login/login_manager.py", line 12, in <module>
    from flask import (_request_ctx_stack, abort, current_app, flash, redirect,
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/ail-framework/AILENV/lib/python3.8/site-packages/markupsafe/__init__.py)
```

This is because markupsafe removed a function used by jinja2, see: https://github.com/pallets/markupsafe/issues?q=is%3Aissue+is%3Aclosed+soft_unicode

There are two workarounds, either setting flask to `1.1.4` (instead of `flask>1.1.2,<=1.1.4`), or setting markupsafe to `markupsafe==2.0.1`.

**Comment by gallypette** [comment]
https://github.com/ail-project/ail-framework/commit/38bc5555d0d41af7791ba94d1ed01458aa0ab535
