### ISSUE TITLE
Investigation MISP export on http

### ISSUE THREAD

**Issue by gallypette** [ail-project/ail-framework#142]
If `misp_url` in `configs/keys/mispKEYS.py` uses an http address, exporting an investigation gives an error 500. It looks like PyMISP does allow creating events on http, fetching is ok though.
All good on https though.

```
[2022-03-16 10:22:18,160] ERROR in app: Exception on /import_export/investigation [GET]
Traceback (most recent call last):
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ail-framework/AILENV/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/root/ail-framework/var/www/./modules/Role_Manager.py", line 68, in decorated_view
    return func(*args, **kwargs)
  File "/root/ail-framework/var/www/blueprints/import_export.py", line 192, in export_investigation
    event_metadata = MispExport.create_investigation_event(investigation_uuid)
  File "/root/ail-framework/bin/export/MispExport.py", line 460, in create_investigation_event
    event_metadata = extract_event_metadata(misp_event)
  File "/root/ail-framework/bin/export/MispExport.py", line 405, in extract_event_metadata
    event_metadata['uuid'] = event['Event']['uuid']
KeyError: 'Event'

```

**Comment by Terrtia** [comment]
Fixed
