### ISSUE TITLE
Bug: Flask doesn't find module ail_typo_squatting and breaks

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#149]
After updating to the current version in the repo flask does break with 
```
Traceback (most recent call last):
  File "./Flask_server.py", line 41, in <module>
    from blueprints.crawler_splash import crawler_splash
  File "/data/AIL/ail-framework/var/www/blueprints/crawler_splash.py", line 28, in <module>
    import Domain
  File "/data/AIL/ail-framework/bin/lib/Domain.py", line 22, in <module>
    import Decoded
  File "/data/AIL/ail-framework/bin/lib/Decoded.py", line 12, in <module>
    import Item
  File "/data/AIL/ail-framework/bin/packages/Item.py", line 29, in <module>
    from objects.abstract_object import AbstractObject
  File "/data/AIL/ail-framework/bin/lib/objects/abstract_object.py", line 21, in <module>
    from lib.Tracker import is_obj_tracked, get_obj_all_trackers
  File "/data/AIL/ail-framework/bin/lib/Tracker.py", line 14, in <module>
    from ail_typo_squatting import runAll
ModuleNotFoundError: No module named 'ail_typo_squatting'
```

**Comment by certrik** [comment]
@Terrtia Hi. This completely prevents the web gui from running.

**Comment by Terrtia** [comment]
Hey @certrik !
DId you encounter any issue with the 4.2 updater ?
The updater should install the ail_typo_squatting library

**Comment by certrik** [comment]
THX for the tip. I executed the updater manually and it works now.
I wouldn't have seen an error while updating from the repo the first time.
