### ISSUE TITLE
AIL Framework not starting v4.2

### ISSUE THREAD

**Issue by lobojc** [ail-project/ail-framework#153]
Hello AIL Framework team, I have the same problem running AIL Framework, the Website doesn't start.

I installed pybgpranking manually because it failed and I updated jsonschema to 4.9.1 

`ERROR: pymisp 2.4.160.1 has requirement jsonschema<5.0.0,>=4.9.1, but you'll have jsonschema 3.2.0 which is incompatible.
`

After check the screens I detected:

1. Flask_AIL ERROR:

```
Flask_base_template.py  create_default_user.py    server.key
Flask_server.py         create_new_web_module.py  static
__pycache__             modules                   templates
blueprints              server.crt                update_thirdparty.sh
Traceback (most recent call last):
  File "./Flask_server.py", line 24, in <module>
    from pytaxonomies import Taxonomies
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/pytaxonomies/__init__.py", line 1, in <module>
    from .api import Taxonomies, Taxonomy, Predicate, Entry
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/pytaxonomies/api.py", line 13, in <module>
    import requests
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
PermissionError: [Errno 1] Operation not permitted: '/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/requests/utils.py'
```

2. Script_AIL ERROR:

```
Flask_base_template.py  create_default_user.py    server.key
Flask_server.py         create_new_web_module.py  static
__pycache__             modules                   templates
blueprints              server.crt                update_thirdparty.sh
Traceback (most recent call last):
  File "./Flask_server.py", line 24, in <module>
    from pytaxonomies import Taxonomies
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/pytaxonomies/__init__.py", line 1, in <module>
    from .api import Taxonomies, Taxonomy, Predicate, Entry
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/pytaxonomies/api.py", line 13, in <module>
    import requests
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
PermissionError: [Errno 1] Operation not permitted: '/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/zmq/sugar/poll.py'
```

3. Redis_AIL info:

```
52383:M 10 Aug 2022 22:27:17.193 # Server initialized
52383:M 10 Aug 2022 22:27:17.193 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
52383:M 10 Aug 2022 22:27:17.193 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
52383:M 10 Aug 2022 22:27:17.193 * Ready to accept connections

```
4. Other screen without error messages !

PS: AIL Starting with ./LAUNCH.sh -l output without ERRORS:

        * Launching Redis servers
        * Launching ARDB servers
        * Launching logging process
        * Launching all the queues
        * Checking configuration
Config File: Nothing to update
Config File: Nothing to update
        * Configuration up-to-date
        * Launching core scripts ...
        * Launching scripts
        * Launching Flask server

Thank you

**Comment by lobojc** [comment]
BTW the errors change every time when I run LAUNCH -k and LAUNCH -l 

1. SOME STOP + START -> 

```
Flask_base_template.py  create_new_web_module.py  static
Flask_server.py         modules                   templates
blueprints              server.crt                update_thirdparty.sh
create_default_user.py  server.key
Traceback (most recent call last):
  File "./Flask_server.py", line 16, in <module>
  File "/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
PermissionError: [Errno 1] Operation not permitted: '/home/ubuntu/ailframework/AILENV/lib/python3.8/site-packages/flask/json/__init__.py'

```

2. Another STOP + START -> 

```
Flask_base_template.py  create_new_web_module.py  static
Flask_server.py         modules                   templates
blueprints              server.crt                update_thirdparty.sh
create_default_user.py  server.key
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 597, in <module>
    main()
  File "/usr/lib/python3.8/site.py", line 580, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.8/site.py", line 498, in venv
    with open(virtual_conf, encoding='utf-8') as f:
PermissionError: [Errno 1] Operation not permitted: '/home/ubuntu/ailframework/AILENV/pyvenv.cfg'

```

**Comment by lobojc** [comment]
Other error details in the installating_steps.sh step:

```
Successfully built pymispgalaxies
Installing collected packages: jsonschema, pymispgalaxies
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 4.9.1
    Uninstalling jsonschema-4.9.1:
      Successfully uninstalled jsonschema-4.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymisp 2.4.160.1 requires jsonschema<5.0.0,>=4.9.1, but you have jsonschema 3.2.0 which is incompatible.
Successfully installed jsonschema-3.2.0 pymispgalaxies-0.2
```

And later -> 

```
Installing collected packages: jsonschema
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 3.2.0
    Uninstalling jsonschema-3.2.0:
      Successfully uninstalled jsonschema-3.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymispgalaxies 0.2 requires jsonschema<4.0,>=3.2, but you have jsonschema 4.9.1 which is incompatible.
Successfully installed jsonschema-4.9.1
Requirement already satisfied: thehive4py in /home/ubuntu/ailframework/AILENV/lib/python3.9/site-packages (1.8.1)
Requirement already satisfied: python-magic in /home/ubuntu/ailframework/AILENV/lib/python3.9/site-packages (from thehive4py) (0.4.27)

```

It looks that some package require one jsonschema version and another package requires a different version

**Comment by lobojc** [comment]
FYI, the same results using python 3.8 and python 3.9, both using Ubuntu 20.04

**Comment by adulau** [comment]
Looking at the error message, I guess it's a mix between the ZMQ library and especially the underlying binding.

`ImportError: libzmq-68c212d3.so.5.2.4: cannot open shared object file: No such file or directory`

For example `libzmq5` would be need to be installed.

**Comment by lobojc** [comment]
Hello @adulau,

I'll check it deeply, but two days ago I removed the folder "4.2" thinking to install version "4.1" and it worked but the "update/current_version" file says "v4.2" even when folder "4.2" doesn't exist, but I don't care if it works \0/
I need to do more "tests" and let the installation process "strong" and with sense, maybe the days ago some "git dependency" was updated and it made the installation work ...

BTW I commented the next lines in the file installing_deps.sh: (installation fails with them)

```
125: shallow clone
126: git fetch --depth=500 --tags --prune
127: if [ ! -z "$TRAVIS" ]; then
128:     echo "Travis detected"
129:     git fetch --unshallow
130: fi
```

Another thing that I detected is that if I want to access to the "Server Management" menu I need to include the github.com ssh-key into ssh_known_hosts file, here the output of the screen "Flask_AIL":

```
10.215.231.1 - - [27/Aug/2022 16:50:34] "GET /PasteSubmit/submit_status?UUID= HTTP/1.1" 200 -
10.215.231.1 - - [27/Aug/2022 16:50:34] "GET /Tags/get_all_tags_galaxies HTTP/1.1" 200 -
10.215.231.1 - - [27/Aug/2022 16:50:34] "GET /Tags/get_all_tags_taxonomies HTTP/1.1" 200 -
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
```

When you accept "yes" or your add the ssh-key of github.com to he file /etc/ssh/ssh_known_hosts then load the "Server Management" page and follow with the file "/static/css/bootstrap4.min.css" and so on:

```
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 10.215.231.1 - - [27/Aug/2022 16:50:41] "GET /settings/ HTTP/1.1" 200 -
10.215.231.1 - - [27/Aug/2022 16:50:41] "GET /static/css/bootstrap4.min.css HTTP/1.1" 304 -
10.215.231.1 - - [27/Aug/2022 16:50:41] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 -
10.215.231.1 - - [27/Aug/2022 16:50:41] "GET /static/js/jquery.js HTTP/1.1" 304 -
10.215.231.1 - - [27/Aug/2022 16:50:41] "GET /static/js/popper.min.js HTTP/1.1" 304 -
```


Thanks for your help and I will let you know if I find more inconvenients
