### ISSUE TITLE
Passive DNS / Internal Server Error

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [ail-project/ail-framework#156]
I´m unable to open Passive DNS under  https://xxx.xxx.xxx.xxx:7000/settings/passivedns because of an Internal Server Error

Here is the output from the Flask Screen:
```
[2022-09-13 11:21:26,377] ERROR in app: Exception on /settings/passivedns [GET]
Traceback (most recent call last):
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "./modules/Role_Manager.py", line 98, in decorated_view
    return func(*args, **kwargs)
  File "/home/itsec/ail-framework/var/www/modules/settings/Flask_settings.py", line 280, in passive_dns
    passivedns_enabled = d4.is_passive_dns_enabled()
  File "/home/itsec/ail-framework/bin/lib/d4.py", line 41, in is_passive_dns_enabled
    r_cache.set('d4:passivedns:enabled', res)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/commands/core.py", line 1673, in set
    return self.execute_command("SET", *pieces, **options)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/client.py", line 1176, in execute_command
    return conn.retry.call_with_retry(
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/client.py", line 1177, in <lambda>
    lambda: self._send_command_parse_response(
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/client.py", line 1152, in _send_command_parse_response
    conn.send_command(*args)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/connection.py", line 796, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/connection.py", line 848, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/home/itsec/ail-framework/AILENV/lib/python3.9/site-packages/redis/connection.py", line 101, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a bytes, string, int or float first.
xxx.xxx.xxx.xxx - - [13/Sep/2022 11:21:26] "GET /settings/passivedns HTTP/1.1" 500 -

```
AIL Version 4.2.1

**Comment by Terrtia** [comment]
Thanks for the report!
Fixed
