### ISSUE TITLE
Lacus Crawler Error

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [ail-project/ail-framework#164]
Hello Team,

i did an upgrade from AIL 4.2 to 5.0 successfully. AIL itself works fine, but i´m struggling with the Lacus Crawler.
Sadly, none crawler (website + onion) works currently. 
Here is the log directly from the start:

```
itsec@ail:~/lacus_proxy/lacus$ poetry run start
Start backend (redis)...
Waiting on cache to start
+ ../../redis/src/redis-server ./cache.conf
done.
Start website...
done.
Start Capture manager...
done.
itsec@ail:~/lacus_proxy/lacus$ No logging config file available.
Falling back on sample config, please initialize the logging config file.
2023-06-19 08:58:18,007 Website INFO:Initializing Website
2023-06-19 08:58:18,009 Website INFO:Launching Website
[2023-06-19 08:58:18 +0200] [13337] [INFO] Starting gunicorn 20.1.0
[2023-06-19 08:58:18 +0200] [13337] [INFO] Listening at: http://0.0.0.0:7100 (13337)
[2023-06-19 08:58:18 +0200] [13337] [INFO] Using worker: sync
[2023-06-19 08:58:18 +0200] [13338] [INFO] Booting worker with pid: 13338
[2023-06-19 08:58:18 +0200] [13339] [INFO] Booting worker with pid: 13339
[2023-06-19 08:58:18 +0200] [13340] [INFO] Booting worker with pid: 13340
[2023-06-19 08:58:18 +0200] [13341] [INFO] Booting worker with pid: 13341
[2023-06-19 08:58:18 +0200] [13342] [INFO] Booting worker with pid: 13342
[2023-06-19 08:58:18 +0200] [13343] [INFO] Booting worker with pid: 13343
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[2023-06-19 08:58:18 +0200] [13345] [INFO] Booting worker with pid: 13345
[2023-06-19 08:58:18 +0200] [13344] [INFO] Booting worker with pid: 13344
[2023-06-19 08:58:18 +0200] [13346] [INFO] Booting worker with pid: 13346
[2023-06-19 08:58:18 +0200] [13347] [INFO] Booting worker with pid: 13347
No logging config file available.
Falling back on sample config, please initialize the logging config file.
2023-06-19 08:58:18,746 CaptureManager INFO:Initializing CaptureManager
2023-06-19 08:58:18,748 CaptureManager INFO:Launching CaptureManager
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2023-06-19 08:59:02,103 LacusCore ERROR:[8913242e-260c-48e3-9025-94db1fde70d8] Something went poorly http://eswpccgr5xyovsahffkehgleqthrasfpfdblwbs4lstd345dwq5qumqd.onion - Executable doesn't exist at /home/itsec/.cache/ms-playwright/webkit-1848/pw_run.sh
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
2023-06-19 10:25:29,423 LacusCore ERROR:[822c0009-94be-4339-809c-8aa44e4336cc] Something went poorly https://www.google.com - Executable doesn't exist at /home/itsec/.cache/ms-playwright/firefox-1408/firefox/firefox
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/lacuscore/lacuscore.py", line 541, in _capture
    async with Capture(
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwrightcapture/capture.py", line 123, in __aenter__
    self.browser = await self.playwright[self.browser_name].launch()
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 14655, in launch
    await self._impl_obj.launch(
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /home/itsec/.cache/ms-playwright/firefox-1408/firefox/firefox
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
2023-06-19 10:25:29,424 LacusCore WARNING:[822c0009-94be-4339-809c-8aa44e4336cc] Unable to capture https://www.google.com: Something went poorly https://www.google.com - Executable doesn't exist at /home/itsec/.cache/ms-playwright/firefox-1408/firefox/firefox
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

```
There exist no ms-playwright inside the .cache folder
```
itsec@ail:~/.cache$ pwd
/home/itsec/.cache
itsec@ail:~/.cache$ ls -lha
total 16K
drwxr-xr-x  4 itsec itsec 4.0K Jun 12 12:55 .
drwxr-xr-x 12 itsec itsec 4.0K Jun 12 12:57 ..
drwxr-xr-x  5 itsec itsec 4.0K Mar 22  2022 pip
drwxr-xr-x  5 itsec itsec 4.0K Jun 12 12:55 pypoetry
itsec@ail:~/.cache$
```
Here is the default lacus conifg i use:
```
itsec@ail:~/lacus_proxy/lacus/config$ cat generic.json
{
    "loglevel": "INFO",
    "website_listen_ip": "0.0.0.0",
    "website_listen_port": 7100,
    "systemd_service_name": "lacus",
    "concurrent_captures": 2,
    "max_capture_time": 3600,
    "only_global_lookups": true,
    "tor_proxy": {
      "server": "socks5://127.0.0.1:9050"
    },
    "_notes": {
        "loglevel": "Can be one of the value listed here: https://docs.python.org/3/library/logging.html#levels",
        "website_listen_ip": "IP Flask will listen on. Defaults to 0.0.0.0, meaning all interfaces.",
        "website_listen_port": "Port Flask will listen on.",
        "systemd_service_name": "(Optional) Name of the systemd service if your project has one.",
        "concurrent_captures": "How many captures can happen at the same (expect ~2Gb of ram/capture)",
        "only_global_lookups": "Set it to True if your instance is publicly available so users aren't able to scan your internal network",
        "max_capture_time": "The very maximal time we allow a capture to keep going. Should only be triggered by captures that cause playwright to never quit, or captures with way too many children.",
        "tor_proxy": "URL to connect to a SOCKS 5 proxy for tor"
    }
}
itsec@ail:~/lacus_proxy/lacus/config$
```
Is there a docker tor_proxy container in the background for Port 9050 or do i need to take care of it ?
Maybe a missed a documentation how to setup it the right way.

Screenshot out of AIL

![AIL](https://github.com/ail-project/ail-framework/assets/50357205/0113fe15-2cd9-4005-b188-6d44faeb975b)

The crawler function never worked for me in version 4.2 either.
Is there any more information i could provide ? Is there a way for me to debug ?

Thanks for any help!

**Comment by certrik** [comment]
And yes you have to take care of the tor_proxy at port 9050 yourself.

**Comment by certrik** [comment]
Lacus install guide has been updated maybe it fixes your errors. 
https://github.com/ail-project/lacus

**Comment by ITSEC-DACHSER** [comment]
> I too had the problem I believe. I resolved it by installing ffmpeg via `sudo apt install ffmpeg`. Afterwards I switched to the virtualenv via `source /home/itsec/.cache/pypoetry/virtualenvs/lacus-B_Bba7K1-py3.9/bin/activate` (in the example I already used your `<home>`) and did `playwright install-deps` followed by `playwright install`. But this probably should be fixed upstream.

Perfect! Installing the playwright packages inside the virtual Environment fixed the problem

**Comment by ITSEC-DACHSER** [comment]
> And yes you have to take care of the tor_proxy at port 9050 yourself.

Ok i understood, thank you very much! 
Wasn´t there the Splash-Manager in version 4.2 to handle Docker containers for this proxy stuff?
Is there any good resource or howto to build a local secure tor proxy for local connections?

Sorry for all these question, but the structure is not complete clear to me, which part is done by the installer and which part needs to be adjusted afterwards manuell.

**Comment by certrik** [comment]
You can for example use `docker run -it -p 127.0.0.1:9050:9050 –-name torproxy -d dperson/torproxy` if you have docker installed on your system already. This will install a pre-configured torproxy running in a docker container.
You have to point ...
```
"tor_proxy": {
      "server": "socks5://127.0.0.1:9050"
    },
``` 
in lacus config to the IP that is stated when you run `docker run ...` command for the torproxy.
At least that should work that way really easily.

**Comment by ITSEC-DACHSER** [comment]
Perfect! I have understood it. Thank you very much for your help. I will close this problem as it was fixed in less than 4 hours. 
(absolutely crazy guys) ;-)

**Comment by Terrtia** [comment]
You need to manually install the tor proxy.
You can use the official tor package repository: https://support.torproject.org/apt/tor-deb-repo/
