### ISSUE TITLE
`500 Internal Server Error` when downloading crawler content if setting `Screenshot is OFF`.

### ISSUE THREAD

**Issue by fukusuket** [ail-project/ail-framework#175]
Hello :) I encountered a minor issue, so I will report it.

**Describe the issue**
`500 Internal Server Error` when downloading crawler content if crawler setting **Screenshot is OFF**.

**Step to Reproduce**
1. [Install ail-framework and launch](https://github.com/ail-project/ail-framework#installation)
2. [Install Lacus and launch](https://github.com/ail-project/lacus#installation)
3. Set `Manual Crawler` (**Screenshot turn OFF**) as follows. and click `Send to Spider`
    1. <img width="1453" alt="スクリーンショット 2023-07-09 12 22 09" src="https://github.com/ail-project/ail-framework/assets/41001169/120b5e5e-7602-4036-9f30-ed1814b37fc2">
4.  After the crawler completes, go to content page and click  `Download Domain content`
    1.  <img width="1453" alt="スクリーンショット 2023-07-09 12 27 55" src="https://github.com/ail-project/ail-framework/assets/41001169/f12cd0ce-328f-4852-930a-b056ec91dd1b">

**Actual behavior**
`500 Internal Server Error` page appears as follows.
<img width="500" alt="スクリーンショット 2023-07-09 12 30 29" src="https://github.com/ail-project/ail-framework/assets/41001169/b88ab059-7fd4-4bd0-8367-c40f9e4a85f5">

**Expected behavior**
500 error page not showing

**Environment**
This issue occurred in the following environment.
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
```
$ python3 -V
Python 3.10.6
```
```
AIL Version | None (release note)
-- | --
Current Branch | master
Current Commit ID | 482fc21b5e93f37982c2c580fb4e710eeac4d9ff
Current Tag | v5.1
```

**Additional context**
- This issue also occurs with the `Onion Crawler`.
- This issue does **not** occur when **Screenshot is ON**.
- The `modules.log` when a 500 error occurs is as follows.
```
2023-07-09 12:29:40,579 Flask_server ERROR:Exception on /crawlers/domain/download [GET]
Traceback (most recent call last):
  File "/home/fukusuke/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fukusuke/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fukusuke/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fukusuke/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fukusuke/ail-framework/AILENV/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/fukusuke/ail-framework/var/www/./modules/Role_Manager.py", line 84, in decorated_view
    return func(*args, **kwargs)
  File "/home/fukusuke/ail-framework/var/www/blueprints/crawler_splash.py", line 373, in crawlers_domain_download
    zip_file = dom.get_download_zip(epoch=epoch)
  File "/home/fukusuke/ail-framework/bin/lib/objects/Domains.py", line 396, in get_download_zip
    screenshot = screenshot['screenshot'].pop()[1:]
KeyError: 'pop from an empty set'
```

**Comment by Terrtia** [comment]
Thank you :)
