### ISSUE TITLE
Flask_server ERROR:Exception on /tracker/add

### ISSUE THREAD

**Issue by kursolface** [ail-project/ail-framework#248]
I tried to add a new tracker and received this error message. How can I fix this problem?

2024-12-19 10:42:34,903 Flask_server ERROR:Exception on /tracker/add [POST]
Traceback (most recent call last):
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/chris/ail-framework/var/www/Role_Manager.py", line 71, in decorated_view
    return func(*args, **kwargs)
  File "/home/chris/ail-framework/var/www/blueprints/hunters.py", line 308, in add_tracked_menu
    res = Tracker.api_add_tracker(input_dict, org, user_id)
  File "/home/chris/ail-framework/bin/lib/Tracker.py", line 1053, in api_add_tracker
    tracker_uuid = create_tracker(tracker_type, to_track, org, user_id, level, description=description, filters=filters,
  File "/home/chris/ail-framework/bin/lib/Tracker.py", line 651, in create_tracker
    return tracker.create(tracker_type, to_track, org, user_id, level, description=description, filters=filters, tags=tags,
  File "/home/chris/ail-framework/bin/lib/Tracker.py", line 466, in create
    self._set_field('creator_org', org)
  File "/home/chris/ail-framework/bin/lib/Tracker.py", line 110, in _set_field
    r_tracker.hset(f'tracker:{self.uuid}', field, value)
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/commands/core.py", line 5033, in hset
    return self.execute_command("HSET", name, *pieces)
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/client.py", line 548, in execute_command
    return conn.retry.call_with_retry(
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/client.py", line 549, in <lambda>
    lambda: self._send_command_parse_response(
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/client.py", line 524, in _send_command_parse_response
    conn.send_command(*args)
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/connection.py", line 477, in send_command
    self._command_packer.pack(*args),
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/connection.py", line 97, in pack
    for arg in map(self.encode, args):
  File "/home/chris/ail-framework/AILENV/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.

**Comment by Terrtia** [comment]
Hey @kursolface !
Your user should be in the default organization.
Are you running the last version ?
Could you please check the settings section to see if your user is part of an organization?

**Comment by kursolface** [comment]
This error appears when I upgrade the AIL framework to the latest version. It occurs not only when adding a new tracker, but also when creating a user or retro hunt. Now I have reinstalled the AIL framework and the error is fixed.
